jessie/micro/Dockerfile, sid/micro/Dockerfile, wheezy/micro/Dockerfile
We need to test the ramifications since regular buildpacks are based on these.
Old size: 
```console
$ docker images buildpack-deps
REPOSITORY       TAG                 IMAGE ID            CREATED             VIRTUAL SIZE
buildpack-deps   sid-micro           5d88036e88d8        About an hour ago   392.2 MB
buildpack-deps   wheezy-micro        9cb126bc1b2b        2 weeks ago         244.4 MB
buildpack-deps   jessie-micro        c8e506fcb72c        2 weeks ago         390.9 MB
```
New size:
```console
REPOSITORY          TAG                 IMAGE ID            CREATED              VIRTUAL SIZE
buildpack-deps      sid-micro           d151033f5745        About a minute ago   294 MB
buildpack-deps      wheezy-micro        4f56dff6b939        About a minute ago   213.2 MB
buildpack-deps …
```
=> Slim down the micro versions

jessie/Dockerfile, sid/Dockerfile, wheezy/Dockerfile
libzlma is (among other things of course) used in Python to build the lzma module. 
Considering it's a small package (and that e.g. zlib is in here), I thought it might make sense to include it here.
Cheers,
=> Add liblzma-dev

squeeze/Dockerfile, squeeze/curl/Dockerfile, squeeze/scm/Dockerfile
I have created buildpack-deps for squeeze.
Squeeze has official image, so I expected it to be supported, it wasn't, hence this pull.
I need squeeze to test that nothing will break/change so I can help few projects/apps to catch up with future/docker.
=> Add squeeze

Dockerfile.template, jessie/Dockerfile, precise/Dockerfile, sid/Dockerfile, squeeze/Dockerfile, stretch/Dockerfile, trusty/Dockerfile, utopic/Dockerfile, vivid/Dockerfile, wheezy/Dockerfile, wily/Dockerfile
Fixes #16.
Closes #20.
```diff
17d16
< ii  build-essentia 11.7         amd64        Informational list of build-essen
36d34
< ii  dpkg-dev       1.17.25      all          Debian package development tools
39d36
< ii  fakeroot       1.20.2-1     amd64        tool for simulating superuser pri
77,79d73
< ii  libalgorithm-d 1.19.02-3    all          module to find differences betwee
< ii  libalgorithm-d 0.04-3+b1    amd64        module to find differences betwee
< ii  libalgorithm-m 0.08-2       all          Perl module for three-way merge o
127d120
< ii  libdpkg-perl   1.17.25      all          Dpkg perl modules
141d133
< ii  libfakeroot:am 1.20.2-1     amd64        tool for simulating superuser pri
145d136
< ii  libfile-fcntll 0.22-1+b1    amd64        Perl module for file locking with …
```
=> Replace `build-essential` meta-package with the actual packages

Dockerfile.template, jessie/Dockerfile, precise/Dockerfile, sid/Dockerfile, squeeze/Dockerfile, stretch/Dockerfile, trusty/Dockerfile, utopic/Dockerfile, vivid/Dockerfile, wheezy/Dockerfile, wily/Dockerfile
Not entirely sure if this process is correct, but I added the dependency into `Dockerfile.template`, then ran `./update.sh` and it seemed to do the right thing.
webp is needed for a number of image processing libraries, and we already have `libjpeg-dev` along with imagemagick packages.
=> Add libwebp-dev

Dockerfile.template-scm, jessie/scm/Dockerfile, precise/scm/Dockerfile, sid/scm/Dockerfile, stretch/scm/Dockerfile, trusty/scm/Dockerfile, vivid/scm/Dockerfile, wheezy/scm/Dockerfile, wily/scm/Dockerfile
This needs to be explicit since stretch has managed to remove "procps" from minbase again! :tada:
=> Add procps to :scm variants since it's fairly common in build systems

Dockerfile.template, jessie/Dockerfile, precise/Dockerfile, sid/Dockerfile, stretch/Dockerfile, trusty/Dockerfile, wheezy/Dockerfile, xenial/Dockerfile
This will fix most of https://github.com/docker-library/python/issues/151, specifically for the regular python variants.
```
After this operation, 167 kB of additional disk space will be used.
```
=> Add libgdbm-dev for python and ruby (libgdbm3 is already pulled in by perl)

generate-stackbrew-library.sh
```console
$ ./generate-stackbrew-library.sh
Maintainers: Tianon Gravi <admwiggin@gmail.com> (@tianon),
Joseph Ferguson <yosifkit@gmail.com> (@yosifkit)
GitRepo: https://github.com/docker-library/buildpack-deps.git
Tags: jessie-curl, curl
GitCommit: a0a59c61102e8b079d568db69368fb89421f75f2
Directory: jessie/curl
Architectures: amd64
Tags: jessie-scm, scm
GitCommit: 1845b3f918f69b4c97912b0d4d68a5658458e84f
Directory: jessie/scm
Architectures: amd64
Tags: jessie, latest
GitCommit: 587934fb063d770d0611e94b57c9dd7a38edf928
Directory: jessie
Architectures: amd64
Tags: sid-curl
GitCommit: a0a59c61102e8b079d568db69368fb89421f75f2
Directory: sid/curl
Architectures: amd64
Tags: sid-scm
GitCommit: 1845b3f918f69b4c97912b0d4d68a5658458e84f
Directory: sid/scm
Architectures: amd64
Tags: sid
GitCommit: …
```
=> Add function to get architectures of parent images so each buildpack image has the same set

Dockerfile.template, artful/Dockerfile, buster/Dockerfile, jessie/Dockerfile, sid/Dockerfile, stretch/Dockerfile, trusty/Dockerfile, wheezy/Dockerfile, xenial/Dockerfile, zesty/Dockerfile
This provides us with `dpkg-architecture`, which is a really useful tool for implementing multi-architecture support (especially when a "GNU triple" is needed).
See https://github.com/docker-library/php/pull/429 for an example of it being used (and links to other PRs using it as well).
=> Add "dpkg-dev" to the full variants

buster/scm/Dockerfile, sid/scm/Dockerfile, update.sh
This is party to resolve the following build failure in current sid, but also partly because bzr usage is esoteric:
```
The following packages have unmet dependencies:
bzr : Depends: python-bzrlib (<= 2.7.0+bzr6622-7.1~) but it is not going to be installed
Depends: python-bzrlib (>= 2.7.0+bzr6622-7) but it is not going to be installed
E: Unable to correct problems, you have held broken packages.
```
=> Remove "bzr" from buster and sid scm variants

Dockerfile.template, artful/Dockerfile, buster/Dockerfile, jessie/Dockerfile, sid/Dockerfile, stretch/Dockerfile, trusty/Dockerfile, wheezy/Dockerfile, xenial/Dockerfile, zesty/Dockerfile
See docker-library/python#235
A number of packages should be built against `libncursesw5` instead of `libncurses5`, most notably, Python. The two libraries do no conflict.
=> Install libncursesw5-dev for ncurses wide character support

Dockerfile-curl.template, debian/stretch/curl/Dockerfile, ubuntu/xenial/curl/Dockerfile
Hi
I can't use apt on stretch image when packages are exposed on https.
It seems package ```apt-transport-https``` present on image ```debian:buster``` do not exists on ```debian:stretch```, so I force installation to allow APT repositories over https.
Thx for your work
=> Add package apt-transport-https

ubuntu/impish/Dockerfile, ubuntu/impish/curl/Dockerfile, ubuntu/impish/scm/Dockerfile, versions.json
While tianon/docker-brew-ubuntu-core#206 is ready for review, let's make some progress on downstream repositories as well.
=> Add Ubuntu Impish

Dockerfile-curl.template, debian/bookworm/curl/Dockerfile, debian/bullseye/curl/Dockerfile, debian/buster/curl/Dockerfile, debian/sid/curl/Dockerfile, ubuntu/bionic/curl/Dockerfile, ubuntu/focal/curl/Dockerfile, ubuntu/jammy/curl/Dockerfile, ubuntu/kinetic/curl/Dockerfile, ubuntu/lunar/curl/Dockerfile
This is pulled in automatically via `gnupg`, and moved from `Recommends` to `Depends` in https://salsa.debian.org/debian/gnupg2/-/commit/99474ad900a8bcdd0e7b68f986fec0013fc01470, which has been part of `src:gnupg2` since 2.1.21-4 (and every supported version of both Debian _and_ Ubuntu here have 2.2.x 😇).
=> Remove explicit `dirmngr` reference

Dockerfile-curl.template, debian/bookworm/curl/Dockerfile, debian/sid/curl/Dockerfile, ubuntu/kinetic/curl/Dockerfile, ubuntu/lunar/curl/Dockerfile
(where new enough to include `sq keyserver` subcommands)
See https://sequoia-pgp.org/ and https://gitlab.com/sequoia-pgp/sequoia-sq
Basic example `sq` workflow:
```console
$ sq keyserver --server hkps://keys.openpgp.org get --output key 'B42F6819007F00F88E364FD4036A9C25BF357DD4'
$ wget https://github.com/tianon/gosu/releases/download/1.16/gosu-amd64{,.asc}
$ sq verify --signer-cert key --detached gosu-amd64.asc gosu-amd64
Good signature from 036A9C25BF357DD4
1 good signature.
```
=> Add "sq" as a "gpg" alternative

Dockerfile-curl.template, debian/trixie/curl/Dockerfile, ubuntu/mantic/curl/Dockerfile
https://tracker.debian.org/news/1478171/rust-sequoia-sq-0310-1-migrated-to-testing/ https://packages.ubuntu.com/sq -> https://launchpad.net/bugs/2036122 (back in "noble" though)
=> Update "sq" availability matrix (yes trixie, no mantic)

Dockerfile-scm.template, Dockerfile.template, debian/bookworm/Dockerfile, debian/bookworm/scm/Dockerfile, debian/bullseye/Dockerfile, debian/bullseye/scm/Dockerfile, debian/buster/Dockerfile, debian/buster/scm/Dockerfile, debian/sid/Dockerfile, debian/sid/scm/Dockerfile, debian/trixie/Dockerfile, debian/trixie/scm/Dockerfile, ubuntu/focal/Dockerfile, ubuntu/focal/scm/Dockerfile, ubuntu/jammy/Dockerfile, ubuntu/jammy/scm/Dockerfile, ubuntu/lunar/Dockerfile, ubuntu/lunar/scm/Dockerfile, ubuntu/mantic/Dockerfile, ubuntu/mantic/scm/Dockerfile, ubuntu/noble/Dockerfile, ubuntu/noble/scm/Dockerfile
Also, switch to using `set -eux` + `;` chains consistently (no more `&&`).
(I have a planned follow-up to this for which https://tracker.debian.org/news/1492892/accepted-apt-278-source-into-unstable/ is a spoiler, but I need a new `debian` rebuilt with APT 2.7.8 in it before I can send that one. :sweat_smile:)
=> Cleanup comments and remove unnecessary conditional

Dockerfile-curl.template, Dockerfile-scm.template, Dockerfile.template, debian/sid/Dockerfile, debian/sid/curl/Dockerfile, debian/sid/scm/Dockerfile, shared.jq
APT [2.7.8](https://tracker.debian.org/news/1492892/accepted-apt-278-source-into-unstable/) has a new `apt-get dist-clean` command designed exactly for our use case of "remove APT lists" and it's much better than our hammer. 🎉
=> Switch to new `apt-get dist-clean` command

debian/trixie/Dockerfile, debian/trixie/curl/Dockerfile, debian/trixie/scm/Dockerfile, shared.jq
As of https://github.com/docker-library/official-images/pull/16155, we're OK to go!! :smile:
=> Add `apt-get dist-clean` to Debian Testing / Trixie 🎉

shared.jq, ubuntu/noble/Dockerfile, ubuntu/noble/curl/Dockerfile, ubuntu/noble/scm/Dockerfile
This has been valid for a while (and I've had it sitting locally on my machine uncommitted for 10 days :joy:), but :partying_face:
=> Update `apt-get dist-clean` logic to include noble

Dockerfile-curl.template, Dockerfile-scm.template, shared.jq
The end result is the same, but the construction is more ergonomic.
=> Use jq's `IN()` instead of `index()`

apply-templates.sh, versions.sh
This is an attempt to help codify #162, and make sure that it's correct / mostly automated.  I'd love to figure out a clean way to help @docker-library-bot be able to make these kinds of updates automatically, but that's a much larger/more complicated problem.
I'm not 100% sold on it, especially how fiddly and frankly unapproachable my filtering method is.
=> Use `bashbrew` to gather the canonical list of supported suites
