- stretch/Dockerfile
- stretch/curl/Dockerfile
- stretch/scm/Dockerfile
Just copy jessie to the next Debian testing release -- stretch.
> Add stretch

- trusty/Dockerfile
- trusty/curl/Dockerfile
- trusty/scm/Dockerfile
Copied wheezy to trusty and modified FROM
> Created ubuntu:trusty files

- Dockerfile.template
- Dockerfile.template-curl
- Dockerfile.template-scm
- precise/Dockerfile
- precise/curl/Dockerfile
- precise/scm/Dockerfile
- update.sh
- utopic/Dockerfile
- utopic/curl/Dockerfile
- utopic/scm/Dockerfile
- vivid/Dockerfile
- vivid/curl/Dockerfile
- vivid/scm/Dockerfile
- wily/Dockerfile
- wily/curl/Dockerfile
- wily/scm/Dockerfile
```console
$ ./update.sh
+ sed 's!SUITE!jessie!g' Dockerfile.template-curl
+ sed 's!SUITE!jessie!g' Dockerfile.template-scm
+ sed 's!SUITE!jessie!g' Dockerfile.template
+ sed 's!SUITE!sid!g' Dockerfile.template-curl
+ sed 's!SUITE!sid!g' Dockerfile.template-scm
+ sed 's!SUITE!sid!g' Dockerfile.template
+ sed 's!SUITE!squeeze!g' Dockerfile.template-curl
+ sed 's!SUITE!squeeze!g' Dockerfile.template-scm
+ sed 's!SUITE!squeeze!g' Dockerfile.template
+ sed 's!SUITE!stretch!g' Dockerfile.template-curl
+ sed 's!SUITE!stretch!g' Dockerfile.template-scm
+ sed 's!SUITE!stretch!g' Dockerfile.template
+ sed 's!SUITE!wheezy!g' Dockerfile.template-curl
+ sed 's!SUITE!wheezy!g' Dockerfile.template-scm
+ sed 's!SUITE!wheezy!g' Dockerfile.template
```
> Officially templatize

- Dockerfile.template
- jessie/Dockerfile
- precise/Dockerfile
- sid/Dockerfile
- stretch/Dockerfile
- trusty/Dockerfile
- vivid/Dockerfile
- wheezy/Dockerfile
- wily/Dockerfile
We have a bunch of other imaging libs, so should probably have png support too.
> Add libpng-dev

- Dockerfile.template
- jessie/Dockerfile
- precise/Dockerfile
- sid/Dockerfile
- stretch/Dockerfile
- trusty/Dockerfile
- wheezy/Dockerfile
- wily/Dockerfile
- xenial/Dockerfile
See https://github.com/docker-library/buildpack-deps/issues/44 and https://github.com/docker-library/python/issues/105.
I hope I have made all necessary edits. Please review, thanks!
Fixes #44
> Add libdb-dev

- Dockerfile.template
- jessie/Dockerfile
- precise/Dockerfile
- sid/Dockerfile
- stretch/Dockerfile
- trusty/Dockerfile
- wheezy/Dockerfile
- xenial/Dockerfile
> Add "libkrb5-dev"

- .travis.yml
- zesty/Dockerfile
- zesty/curl/Dockerfile
- zesty/scm/Dockerfile
Newly added Dockerfiles and Travis job entry are generated from _update.sh_.
> Add ubuntu:zesty

- Dockerfile.template
- jessie/Dockerfile
- precise/Dockerfile
- sid/Dockerfile
- stretch/Dockerfile
- trusty/Dockerfile
- wheezy/Dockerfile
- xenial/Dockerfile
- yakkety/Dockerfile
- zesty/Dockerfile
See https://lists.debian.org/debian-devel-announce/2016/09/msg00000.html for more details.
> Properly swap from "libmysqlclient-dev" to "default-libmysqlclient-dev" where appropriate

- Dockerfile-curl.template
- artful/curl/Dockerfile
- buster/curl/Dockerfile
- jessie/curl/Dockerfile
- sid/curl/Dockerfile
- stretch/curl/Dockerfile
- trusty/curl/Dockerfile
- wheezy/curl/Dockerfile
- xenial/curl/Dockerfile
- zesty/curl/Dockerfile
See https://github.com/docker-library/python/issues/236 for details.
> Swap from "gnupg2" to "gnupg"

- generate-stackbrew-library.sh
> Update "generate-stackbrew-library.sh" to include Debian aliases like "stable", etc

- Dockerfile.template
- bionic/Dockerfile
- buster/Dockerfile
- cosmic/Dockerfile
- disco/Dockerfile
- jessie/Dockerfile
- sid/Dockerfile
- stretch/Dockerfile
- trusty/Dockerfile
- wheezy/Dockerfile
- xenial/Dockerfile
See:
- https://github.com/ruby/ruby/commit/83a0709174f9f99038b45914ee54acd7c126f11b
- https://www.npmjs.com/package/gmplib
- https://pypi.org/project/gmpy/ + https://pypi.org/project/gmpy2/
- https://github.com/ncw/gmp
> Add "libgmp-dev"

- Dockerfile.template
- bionic/Dockerfile
- bullseye/Dockerfile
- buster/Dockerfile
- cosmic/Dockerfile
- disco/Dockerfile
- eoan/Dockerfile
- jessie/Dockerfile
- sid/Dockerfile
- stretch/Dockerfile
- update.sh
- xenial/Dockerfile
> Replace (defunct) "libgeoip-dev" with "libmaxminddb-dev" (where available)

- Dockerfile.template
- bionic/Dockerfile
- bullseye/Dockerfile
- buster/Dockerfile
- eoan/Dockerfile
- focal/Dockerfile
- jessie/Dockerfile
- sid/Dockerfile
- stretch/Dockerfile
- xenial/Dockerfile
Same as https://github.com/docker-library/mongo/pull/381
See also, https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=929417
> Fix hang while trying to build some images

- Dockerfile-curl.template
- Dockerfile.template
- debian/bullseye/curl/Dockerfile
- debian/sid/curl/Dockerfile
- debian/stretch/curl/Dockerfile
- ubuntu/bionic/Dockerfile
- ubuntu/bionic/curl/Dockerfile
- ubuntu/focal/curl/Dockerfile
- ubuntu/groovy/Dockerfile
- ubuntu/groovy/curl/Dockerfile
- ubuntu/hirsute/Dockerfile
- ubuntu/hirsute/curl/Dockerfile
- ubuntu/hirsute/scm/Dockerfile
- ubuntu/xenial/Dockerfile
- ubuntu/xenial/curl/Dockerfile
- versions.json
Signed-off-by: You-Sheng Yang <vicamo@gmail.com>
> Add Ubuntu Hirsute

- debian/bookworm/Dockerfile
- debian/bookworm/curl/Dockerfile
- debian/bookworm/scm/Dockerfile
- versions.json
> Add Debian Bookworm

- ubuntu/kinetic/Dockerfile
- ubuntu/kinetic/curl/Dockerfile
- ubuntu/kinetic/scm/Dockerfile
- versions.json
Signed-off-by: You-Sheng Yang (vicamo) <vicamo@gmail.com>
> Add Ubuntu Kinetic 22.10

- ubuntu/lunar/Dockerfile
- ubuntu/lunar/curl/Dockerfile
- ubuntu/lunar/scm/Dockerfile
- versions.json
Signed-off-by: You-Sheng Yang (vicamo) <vicamo@gmail.com>
> Add Ubuntu Lunar Lobster 23.04

- Dockerfile-curl.template
- debian/trixie/Dockerfile
- debian/trixie/curl/Dockerfile
- debian/trixie/scm/Dockerfile
- versions.json
Following same pattern as https://github.com/docker-library/buildpack-deps/pull/124
> Add Debian Trixie (testing)

- ubuntu/noble/Dockerfile
- ubuntu/noble/curl/Dockerfile
- ubuntu/noble/scm/Dockerfile
- versions.json
> Add Ubuntu Noble (24.04)

- ubuntu/questing/Dockerfile
- ubuntu/questing/curl/Dockerfile
- ubuntu/questing/scm/Dockerfile
- versions.json
(This is the result of running `./update.sh`, per https://github.com/docker-library/buildpack-deps/pull/164)
> Add Ubuntu Questing Quokka
